#!/bin/bash
set -euo pipefail

# Sign a DMG with EdDSA and generate/update appcast.xml for Sparkle
#
# Prerequisites:
#   - ~/sparkle-tools/sign_update (from Sparkle 2 release)
#   - EdDSA private key in macOS Keychain (generated by ~/sparkle-tools/generate_keys)
#
# Usage:
#   ./update-appcast.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
DMG_PATH="$PROJECT_DIR/dist/Tab Switcher.dmg"
APPCAST_PATH="$PROJECT_DIR/docs/appcast.xml"
SIGN_TOOL="${SIGN_TOOL:-$HOME/sparkle-tools/sign_update}"

if [ ! -f "$DMG_PATH" ]; then
    echo "ERROR: DMG not found at $DMG_PATH"
    echo "Run build.sh first."
    exit 1
fi

if [ ! -f "$SIGN_TOOL" ]; then
    echo "ERROR: sign_update tool not found at $SIGN_TOOL"
    echo "Download Sparkle 2 and copy bin/sign_update to ~/sparkle-tools/"
    exit 1
fi

# Get version from Info.plist
APP_BUNDLE="$PROJECT_DIR/dist/Tab Switcher.app"
VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$APP_BUNDLE/Contents/Info.plist")
echo "Version: $VERSION"

# Get DMG file size
FILE_SIZE=$(stat -f%z "$DMG_PATH")
echo "DMG size: $FILE_SIZE bytes"

# Sign the DMG with EdDSA
echo "==> Signing DMG with EdDSA..."
SIGNATURE=$("$SIGN_TOOL" "$DMG_PATH" | grep 'edSignature=' | sed 's/.*edSignature="\([^"]*\)".*/\1/')

if [ -z "$SIGNATURE" ]; then
    echo "ERROR: Failed to get EdDSA signature"
    exit 1
fi
echo "Signature: ${SIGNATURE:0:20}..."

# Generate appcast.xml
echo "==> Generating appcast.xml..."
cat > "$APPCAST_PATH" << EOF
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <channel>
        <title>Tab Switcher Updates</title>
        <item>
            <title>Version $VERSION</title>
            <sparkle:version>$VERSION</sparkle:version>
            <sparkle:shortVersionString>$VERSION</sparkle:shortVersionString>
            <sparkle:minimumSystemVersion>14.0</sparkle:minimumSystemVersion>
            <enclosure url="https://tabswitcher.app/Tab%20Switcher.dmg"
                type="application/octet-stream"
                sparkle:edSignature="$SIGNATURE"
                length="$FILE_SIZE" />
        </item>
    </channel>
</rss>
EOF

echo "==> Done! Appcast written to $APPCAST_PATH"
echo "   Don't forget to update docs/version.json to match."
